name: Vulnerability Training Check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  security-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: secureflag/actions/.github/actions/advisory_training_check@main
        with:
          target_repo: ${{ github.repository }}
          gh_token: ${{ secrets.SEC_TOKEN }}
          api_endpoint: ${{ secrets.API_ENDPOINT }}
          api_token: ${{ secrets.API_TOKEN }}
