name: Vulnerability Training Check

on:
  push:
    branches:
      - '**'
    branches-ignore:
      - 'main'  # Or your default branch name

jobs:
  security-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: secureflag/actions/.github/actions/advisory_training_check@main  # Your action repo
        with:
          target_repo: ${{ github.repository }}  # Or specify another repo
          sec_token: ${{ secrets.SEC_TOKEN }}
          api_endpoint: ${{ secrets.API_ENDPOINT }}
          api_token: ${{ secrets.API_TOKEN }}
